- hosts: localhost
  vars_prompt:
  - name: "git_user"
    prompt: "What is your Git username?"
    private: no
  - name: "git_email"
    prompt: "What is your Git email?"
    private: no
  - name: "clitools"
    prompt: "Do you need cli tools? (vim, curl, wget, htop) [y/N]"
    private: no
  - name: "officetools"
    prompt: "Do you need office tools? (shutter, keepassx, thunderbird) [y/N]"
    private: no
  - name: "development"
    prompt: "Do you need development tools? (git, gcm, remmina, virtualbox, vagrant) [y/N]"
    private: no
  - name: "vpn"
    prompt: "Do you need Gnome VPN extensions? [y/N]"
    private: no
  - name: "dbclient"
    prompt: "Do you need pgAdmin [1] or DBeaver [2]? [1,2,N]"
    private: no
  - name: "editor"
    prompt: "Do you need Atom [1] or Visual Studio Code [2]? [1,2,N]"
    private: no
  - name: "browser"
    prompt: "Do you need Chromium [1] or Opera [2]? [1,2,N]"
    private: no 
  - name: "java"
    prompt: "Do you need Java? [y/N]"
    private: no
  - name: "seafile"
    prompt: "Do you need Seafile? [y/N]"
    private: no
  - name: "spotify"
    prompt: "Do you need Spotify? [y/N]"
    private: no
  - name: "zsh"
    prompt: "Do you need zsh as default shell? [y/N]"
    private: no
  pre_tasks:
    - include_vars: config/defaults.yml
  roles:
  - { role: updates }
  - { role: clitools,     when: clitools|lower == "y" }
  - { role: officetools,  when: officetools|lower == "y" }
  - { role: chromium,     when: "'1' in browser" }
  - { role: opera,        when: "'2' in browser" }
  - { role: git,          when: development|lower == "y" }
  - { role: gcm,          when: development|lower == "y" }
  - { role: remmina,      when: development|lower == "y" }
  - { role: virtualbox,   when: development|lower == "y" }
  - { role: vagrant,      when: development|lower == "y" }
  - { role: vpn_ext,      when: vpn|lower == "y" }
  - { role: pgadmin,      when: "'1' in dbclient" }
  - { role: dbeaver,      when: "'2' in dbclient" }
  - { role: atom,         when: "'1' in editor" }
  - { role: vscode,       when: "'2' in editor" }
  - { role: java,         when: java|lower == "y" }
  - { role: seafile,      when: seafile|lower == "y" }
  - { role: spotify,      when: spotify|lower == "y" }
  - { role: zsh,          when: zsh|lower == "y" }
