##################################################
### Install packages
- name: Add apt key
  become: true
  apt_key: url={{ opera_repository_key }} state=present

- name: Add repository
  become: true
  apt_repository: repo="deb [arch=amd64] {{ opera_repository }} stable non-free" state=present update_cache=yes

- name: Install packages
  become: true
  apt: name={{ item }} state=latest allow_unauthenticated=yes
  with_items:
    - opera-stable
