# Atom
atom_ppa: ppa:webupd8team/atom

# Visual Studio Code
vscode_repository_key: https://packages.microsoft.com/keys/microsoft.asc
vscode_repository: http://packages.microsoft.com/repos/vscode

# GCM
gcm_url: https://neikei.github.io/software/
gcm_package: gnome-connection-manager_1.1.0-1.deb

# Opera
opera_repository_key: https://deb.opera.com/archive.key
opera_repository: https://deb.opera.com/opera-stable/

# pgAdmin
pgadmin_repository_key: https://www.postgresql.org/media/keys/ACCC4CF8.asc
pgadmin_repository: http://apt.postgresql.org/pub/repos/apt/

# DBeaver
dbeaver_url: http://dbeaver.jkiss.org/files/
dbeaver_package: dbeaver-ce_latest_amd64.deb

# Seafile
seafile_ppa: ppa:seafile/seafile-client

# Virutalbox
vbox_repository_keys: [ 'http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc', 'http://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc' ]
vbox_repository: http://download.virtualbox.org/virtualbox/debian
vbox_version: 5.2

# Vagrant
vagrant_version: 2.2.1
vagrant_url: https://releases.hashicorp.com/vagrant/{{ vagrant_version }}
vagrant_package: vagrant_{{ vagrant_version }}_x86_64.deb

# Unneeded packages
cleanup_packages:
  - ubuntu-web-launchers
  - whoopsie
  - apport
  - apport-gtk